name: Deploy to Salesforce (JWT)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-sandbox
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: sandbox
    timeout-minutes: 60
    env:
      SF_API_VERSION: ${{ vars.SF_API_VERSION || '61.0' }}

    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v4
        with:
          # Fetches the merge commit, which contains all changes from the PR branch
          # merged into the base branch (main).
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm i -g @salesforce/cli@${{ vars.SF_CLI_VERSION || 'latest' }} && sf --version

      - name: Authenticate to Salesforce (JWT)
        run: |
          set -euo pipefail
          trap 'shred -u server.key || rm -f server.key' EXIT
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          chmod 600 server.key

          sf org login jwt \
            --username "${{ secrets.SF_USERNAME }}" \
            --client-id "${{ secrets.SF_CONSUMER_KEY }}" \
            --jwt-key-file server.key \
            --instance-url "${{ vars.SF_INSTANCE_URL }}" \
            --alias target --set-default
          
          sf config set org-api-version="$SF_API_VERSION"

      - name: Validate in sandbox (dry-run with tests)
        run: |
          sf project deploy start \
            --target-org target \
            --source-dir force-app \
            --dry-run \
            --test-level RunLocalTests \
            --wait 90
